#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil tex:t
#+TITLE: MathematicaStan
#+SUBTITLE: A Mathematica package to interact with CmdStan
#+AUTHOR: Picaud Vincent

* Introduction

*MathematicaStan* is a package to ease the interaction with [[http://mc-stan.org/interfaces/cmdstan][CmdStan]]
from Mathematica. It is tested under *Linux* with *Mathematica version >=8.0*.

*Author & contact:* picaud.vincent at gmail.com

*Disclaimer*: this is the first *beta* version, not yet tested under Windows.

* Getting started

** Installation

*** Creation of the CmdStan.m file (*not required*)

You can skip this step, a [[https://github.com/vincent-picaud/MathematicaStan/blob/master/CmdStan.m][CmdStan.m]] file is already present in this directory.

You just have to know that the [[https://github.com/vincent-picaud/MathematicaStan/blob/master/CmdStan.m][CmdStan.m]] file is automatically created
from the [[https://github.com/vincent-picaud/MathematicaStan/blob/master/CmdStan.org][CmdStan.org]] file.  However for your convenience, you do not
have to create a fresh *CmdStan.m*, I have directly included its last
version.

*** CmdStan installation 

First you must install [[http://mc-stan.org/interfaces/cmdstan][CmdStan]]. Once this is done you get a directory containing stuff like:

#+BEGIN_EXAMPLE
bin  examples  LICENSE  make  makefile  README.md  runCmdStanTests.py  src  stan  test-all.sh
#+END_EXAMPLE

In my case, *CmdStan* is installed there:
#+BEGIN_EXAMPLE
~/GitHub/cmdstan
#+END_EXAMPLE


*** CmdStan.m installation

Download the package *CmdStan.m* and open it with *Mathematica*. The
simplest way to install the package is to go to the Mathematica
*File->Install* Menu, then follow the instructions.

*** CmdStan.m configuration

There are two possibilities:

- You define where [[http://mc-stan.org/interfaces/cmdstan][CmdStan]] is installed for each Mathematica session:
#+BEGIN_SRC mathematica :exports code
Needs["CmdStan`"];
StanSetDirectory["YOUR_PATH/cmdstan"];
#+END_SRC

#+RESULTS:
: CmdStanError::stanDirNotFound: CmdStan install directory "YOUR_PATH/cmdstan" not found.

- You define once for all, the *stanDir* variable in the package code source. 
  Your *CmdStan.m* package, after installation, is generally stored there (at least under Linux):
#+BEGIN_EXAMPLE
~/.Mathematica/Applications/CmdStan.m
#+END_EXAMPLE
  edit it and modify the line:
#+BEGIN_EXAMPLE
(* You can modify me (initial configuration) *)
stanDir="~/GitHub/cmdstan"; 
#+END_EXAMPLE
  according to your configuration.


** Complete examples

** Bernoulli.stan 

We use the Examples/Bernoulli/bernoulli.stan example. You can find the
Mathematica notebook [[https://github.com/vincent-picaud/MathematicaStan/blob/master/Examples/Bernoulli/bernoulli.nb][benoulli.nb]] or directly view the associated
[[https://github.com/vincent-picaud/MathematicaStan/blob/master/Examples/Bernoulli/bernoulli.pdf][bernoulli.pdf]] file.

** soft-k-means.stan example

This use case is based on the [[https://github.com/stan-dev/example-models/blob/master/misc/cluster/soft-k-means/soft-k-means.stan][soft-k-means]] example. 

You can find the Mathematica notebook [[https://github.com/vincent-picaud/MathematicaStan/blob/master/Examples/Cluster/soft-k-means.nb][soft-k-means.nb]] or directly view
the associated [[https://github.com/vincent-picaud/MathematicaStan/blob/master/Examples/Cluster/soft-k-means.pdf][soft-k-means.pdf]] file.


** horseShoePrior.stan example

This example is a partial reproduction of the blog post [[https://ariddell.org/horseshoe-prior-with-stan.html][Epistemology
of the corral: regression and variable selection with Stan and the
Horseshoe prior]]. Also see [[http://andrewgelman.com/2015/02/17/bayesian-survival-analysis-horseshoe-priors/#comment-211738][Bayesian survival analysis with horseshoe priors—in Stan!]]

You can find the Mathematica notebook [[https://github.com/vincent-picaud/MathematicaStan/blob/master/Examples/HorseShoePrior/horseShoePrior.nb][horseShoePrior.nb]] or directly view
the associated [[https://github.com/vincent-picaud/MathematicaStan/blob/master/Examples/HorseShoePrior/horseShoePrior.pdf][horseShoePrior.pdf]] file.


* Package documentation

** Complete list of commands

The complete list of commands is:

#+BEGIN_SRC mathematica :exports both
Needs["CmdStan`"];
?CmdStan`*
#+END_SRC

#+RESULTS:
#+begin_example
RDumpExport
StanCompile
StanDirectory
StanFindVariableColumn
StanFindVariableIndex
StanGetOptionOptimize
StanGetOptionSample
StanGetOptionVariational
StanImport
StanImportComment
StanImportData
StanImportHeader
StanImportReplaceData
StanOptionOptimize
StanOptionSample
StanOptionVariational
StanRemoveOptionOptimize
StanRemoveOptionSample
StanRemoveOptionVariational
StanResetOptionOptimize
StanResetOptionSample
StanResetOptionVariational
StanRunOptimize
StanRunSample
StanRunVariational
StanSetDirectory
StanSetOptionOptimize
StanSetOptionSample
StanSetOptionVariational
StanVariable
StanVariableColumn
StanVariableFunc
StanVariableToImport
#+end_example

To get extra information you can use the inline package documentation, for intance:

#+BEGIN_SRC mathematica :exports both
Needs["CmdStan`"];
?RDumpExport
#+END_SRC

#+RESULTS:
: RDumpExport[fileNameDataR_?StringQ,listOfNameValue_]
: 
: Creates a file and dump data in RDump format.
: 
: Note:
:  - input data "listOfNameValue" is of the form 
:    {{"MatrixName",{{...}}},{"ScalarName",5.6},{"VectorName",{..}},...}
:  - if "fileName" has no extension, ".data.R" is automatically added.


